name: Genshin & Star Rail Codes

on:
  workflow_dispatch:

concurrency:
  group: codes-bot
  cancel-in-progress: false

permissions:
  contents: write

jobs:

  run-bot:

    runs-on: ubuntu-latest

    steps:

      # ==========================================
      # RÉCUPÉRER LE PROJET
      # ==========================================

      - name: Récupérer le code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      # ==========================================
      # CONFIGURER GIT
      # ==========================================

      - name: Configurer Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"


      # ==========================================
      # INSTALLER PYTHON
      # ==========================================

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      # ==========================================
      # INSTALLER LES DÉPENDANCES
      # ==========================================

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium


      # ==========================================
      # LANCER LE BOT
      # ==========================================

      - name: Lancer le bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: "1494316922534367352"
        run: |
          python bot.py


      # ==========================================
      # SAUVEGARDER LES MODIFICATIONS
      # ==========================================

      - name: Sauvegarder les modifications
        if: always()
        run: |

          git add .

          git diff --cached --quiet || git commit -m "Update codes and bot status"

          git pull --rebase origin main

          git push origin main


      # ==========================================
      # FIN
      # ==========================================

      - name: Terminé
        if: always()
        run: |
          echo "========================================"
          echo "Workflow terminé."
          echo "========================================"
